category_new:
    path:     /category
    defaults: { _controller: ApiBundle:Category:new }
    methods:  POST

category_show:
    path:     /category/{name}
    defaults: { _controller: ApiBundle:Category:show }
    methods:  GET

category_list:
    path:     /categories
    defaults: { _controller: ApiBundle:Category:list }
    methods:  GET

category_update:
    path:     /category/{name}
    defaults: { _controller: ApiBundle:Category:update }
    methods:  PUT|PATCH

category_delete:
    path:     /category/{name}
    defaults: { _controller: ApiBundle:Category:delete }
    methods:  DELETE


actor_new:
    path:     /actor
    defaults: { _controller: ApiBundle:Actor:new }
    methods:  POST

actor_show:
    path:     /actor/{name}
    defaults: { _controller: ApiBundle:Actor:show }
    methods:  GET

actor_list:
    path:     /actors
    defaults: { _controller: ApiBundle:Actor:list }
    methods:  GET

actor_update:
    path:     /actor/{name}
    defaults: { _controller: ApiBundle:Actor:update }
    methods:  PUT|PATCH

actor_delete:
    path:     /actor/{name}
    defaults: { _controller: ApiBundle:Actor:delete }
    methods:  DELETE