category_new:
    path:     /category/new
    defaults: { _controller: ApiBundle:Category:new }
    methods:  POST

category_show:
    path:     /category/{name}
    defaults: { _controller: ApiBundle:Category:show }
    methods:  GET

category_list:
    path:     /categories
    defaults: { _controller: ApiBundle:Category:list }
    methods:  GET

category_update:
    path:     /category/{name}
    defaults: { _controller: ApiBundle:Category:update }
    methods:  PUT|PATCH

category_delete:
    path:     /category/{name}
    defaults: { _controller: ApiBundle:Category:delete }
    methods:  DELETE